name: CustomQuery
version: 1.1.1-BETA
api: 3.0.0
main: CustomQuery\iZeaoGamer\Main
description: "A customizable query plugin, where you can configure anything that relates to Querying your server."

virions:
- UpdateNotifier
- ConfigUpdater