name: CustomQuery
version: 1.0.2-ALPHA
api: 3.0.0
main: CustomQuery\iZeaoGamer\Main
description: "A customizable query plugin, where you can configure anything that relates to Querying your server."
commands:
  customquery:
    aliases: ["cq", "query"]
    description: Set your query settings in game!
permissions:
  customquery.settings:
    default: op
    description: "CustomQuery settings permission."
